### ISSUE TITLE
onTick fails

### ISSUE THREAD

**Issue by pixelrebel** [PavelVanecek/hubot-cronjob#1]
``` coffeescript
HubotCron = require 'hubot-cronjob'

module.exports = (robot) ->
  tz = 'America/Los_Angeles'
  new HubotCron '* * * * *', tz, auditCheck

  auditCheck = () ->
    robot.logger.debug 'cron auditCheck triggered'
```

```
[Mon Oct 05 2015 15:28:00 GMT-0700 (PDT)] ERROR TypeError: undefined is not a function
  at HubotCron.onTick (/opt/hubot/node_modules/hubot-cronjob/src/cronjob.coffee:24:5, <js>:21:38)
  at [object Object].callbackWrapper [as _onTimeout] (/opt/hubot/node_modules/hubot-cronjob/node_modules/cron/lib/cron.js:427:24)
  at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by PavelVanecek** [comment]
The issue is you are using the function before is declared. If I switch the code in your example, it works:

```
module.exports = (robot) ->
  tz = 'America/Los_Angeles'

  auditCheck = ->
    robot.logger.debug 'cron auditCheck triggered'

  new HubotCron '* * * * * *', tz, auditCheck
```

I added a simple check to make this more readable: https://github.com/PavelVanecek/hubot-cronjob/commit/362e63291b450bf3245903273d31ac5538f2178e

**Comment by pixelrebel** [comment]
Thanks @PavelVanecek!
